use_frameworks!

target 'NetworkService_Example' do

	pod 'Alamofire', '~> 4.0'
	pod 'ObjectMapper', '~> 2.2'
	pod 'NetworkService', :path => '../'

  target 'NetworkService_Tests' do
    inherit! :search_paths

  end
end
